name: ecommerce_flutter_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ">=3.7.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^3.12.1  # Latest stable version
  firebase_auth: ^5.5.1  # Latest stable version
  cloud_firestore: ^5.6.5  # Latest stable version
  firebase_auth_web: ^5.14.1  # Latest stable version
  cloud_firestore_web: ^4.4.5  # Latest stable version
  js: ^0.7.2  # Latest stable version
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
