// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCnSq420syS9OHhsynq9CExLom9nAJGT7Y',
    appId: '1:182408837136:web:ac26118a8a09605d62f295',
    messagingSenderId: '182408837136',
    projectId: 'ecommerce-flutter-app-dd92c',
    authDomain: 'ecommerce-flutter-app-dd92c.firebaseapp.com',
    storageBucket: 'ecommerce-flutter-app-dd92c.firebasestorage.app',
    measurementId: 'G-6MWVQHXM98',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDrIYTLAihu--ndB4xt-z-3LczWIczJ3fg',
    appId: '1:182408837136:android:89824d78f798633562f295',
    messagingSenderId: '182408837136',
    projectId: 'ecommerce-flutter-app-dd92c',
    storageBucket: 'ecommerce-flutter-app-dd92c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD9qqXrNNEmlZJCD7HEWEG1rC5D4nFXk2o',
    appId: '1:182408837136:ios:48024c8471c14ed262f295',
    messagingSenderId: '182408837136',
    projectId: 'ecommerce-flutter-app-dd92c',
    storageBucket: 'ecommerce-flutter-app-dd92c.firebasestorage.app',
    iosBundleId: 'com.example.ecommerceFlutterApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD9qqXrNNEmlZJCD7HEWEG1rC5D4nFXk2o',
    appId: '1:182408837136:ios:48024c8471c14ed262f295',
    messagingSenderId: '182408837136',
    projectId: 'ecommerce-flutter-app-dd92c',
    storageBucket: 'ecommerce-flutter-app-dd92c.firebasestorage.app',
    iosBundleId: 'com.example.ecommerceFlutterApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCnSq420syS9OHhsynq9CExLom9nAJGT7Y',
    appId: '1:182408837136:web:ac2d9269eb944a0d62f295',
    messagingSenderId: '182408837136',
    projectId: 'ecommerce-flutter-app-dd92c',
    authDomain: 'ecommerce-flutter-app-dd92c.firebaseapp.com',
    storageBucket: 'ecommerce-flutter-app-dd92c.firebasestorage.app',
    measurementId: 'G-RJFW3LGSM2',
  );
}
